const assert=require('assert').strict,fs=require('fs'),path=require('path');const R=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(R,'public/index.html'),'utf8'),free=fs.readFileSync(path.join(R,'public/js/freeroam.js'),'utf8'),friends=fs.readFileSync(path.join(R,'public/js/friends.js'),'utf8'),worker=fs.readFileSync(path.join(R,'src/worker.mjs'),'utf8'),auth=fs.readFileSync(path.join(R,'src/auth.mjs'),'utf8'),migration=fs.readFileSync(path.join(R,'migrations/0004_friend_requests.sql'),'utf8');
for(const id of ['friendsBtn','friends','friendRequestsSection','friendOutgoingSection','freeServers','freeRoam','freeCanvas','freeChatPanel','freeChatPreview','freeMapPanel','freeMapClear','freeContextAction'])assert.ok(html.includes(`id="${id}"`),`missing ${id}`);
for(const token of ['/api/free/servers','activity_join','activity_finish','free_chat','free_state','FREE_MAX_PLAYERS=20'])assert.ok(worker.includes(token),`worker missing ${token}`);
for(const token of ['/api/friends/request','/api/friends/accept','/api/friends/decline','/api/friends/cancel','/api/friends/remove','friend_requests','user_presence','friendships'])assert.ok(auth.includes(token),`auth missing ${token}`);
for(const token of ['CREATE TABLE IF NOT EXISTS friend_requests','idx_friend_requests_to','idx_friend_requests_from'])assert.ok(migration.includes(token),`migration missing ${token}`);
for(const token of ['AIRPORT DRAG','SPEED TRAP','PORT DRIFT','CAR MEET','MOUNTAIN PASS','R.RACE_PHYSICS','car.update(dt','driftPhysicsTime','МЕТКА УДАЛЕНА'])assert.ok(free.includes(token),`free roam missing ${token}`);
assert.ok(friends.includes('/api/friends/request'));assert.ok(friends.includes('respond(requestId'));assert.ok(friends.includes('/api/friends/${action}')); assert.ok(html.includes('js/freeroam.js')&&html.includes('js/friends.js'));
console.log('freeroam_social_smoke: OK');
