/* Porsche/category feature validation. Run: node tests/porsche_shop_smoke.js */
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..');global.window=global;window.Racing={};
vm.runInThisContext(fs.readFileSync(path.join(ROOT,'public/js/content.js'),'utf8'),{filename:'js/content.js'});
const R=global.Racing,assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
const real=R.REAL_CAR_IDS.map(id=>[id,R.LIVERIES[id]]),basic=real.filter(([,x])=>x.category==='basic'),sport=real.filter(([,x])=>x.category==='sport'),premium=real.filter(([,x])=>x.category==='premium');
assert(basic.length===6,'basic must contain six real cars');assert(sport.length===7,'sport must contain seven real cars');assert(premium.length===6,'premium must contain six real cars');
assert(R.normalizeCarCategory('regular')==='basic','legacy regular must normalize to basic');
const p=R.LIVERIES['porsche-911'];assert(p.name==='Porsche 911 Turbo S'&&p.price===85000&&p.currency==='CR'&&p.category==='premium'&&p.sprite&&p.sprite.src&&p.sprite.thumbnail,'Porsche metadata/assets missing');
assert(p.sprite.raceScale>=1.15&&p.sprite.raceScale<=1.32,'Porsche raceScale out of tuned range');assert(p.sprite.previewScale>=1.12&&p.sprite.previewScale<=1.30,'Porsche previewScale out of range');assert(p.sprite.preserveAspectRatio===true,'Porsche must preserve source aspect ratio');
for(const rel of [p.sprite.src,p.sprite.thumbnail])assert(fs.existsSync(path.join(ROOT,'public',rel)),`missing asset ${rel}`);
let s=R.normalizeSave({credits:84999});assert(R.shopAction(s,'livery','porsche-911')==='insufficient'&&s.credits===84999,'84999 CR scenario failed');
s=R.normalizeSave({credits:85000});assert(R.shopAction(s,'livery','porsche-911')==='purchased'&&s.credits===0,'85000 CR purchase failed');assert(R.shopAction(s,'livery','porsche-911')==='selected'&&s.credits===0&&s.selectedLivery==='porsche-911','repeat purchase/select protection failed');s=R.normalizeSave(s);assert(s.ownedLiveries.includes('porsche-911')&&s.selectedLivery==='porsche-911','save persistence normalization failed');
const html=fs.readFileSync(path.join(ROOT,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(ROOT,'public/css/style.css'),'utf8'),garage=fs.readFileSync(path.join(ROOT,'public/js/garage.js'),'utf8'),car=fs.readFileSync(path.join(ROOT,'public/js/car.js'),'utf8');
for(const cat of ['all','basic','sport','premium','rare','legendary','lux'])assert(html.includes(`data-category="${cat}"`),`missing ${cat} category tab`);
assert(garage.includes('R.getCatalogEntries')&&garage.includes("'thumbnail'"),'catalog filter/thumbnail path missing');assert(css.includes('.shop-item.rarity-premium')&&css.includes('.shop-item.rarity-lux::before')&&css.includes('luxCardShimmer'),'premium/LUX styles missing');assert(car.includes('this.spriteSpec')&&car.includes('drawImage(this.spriteImage'),'gameplay sprite renderer missing');assert(car.includes('resolveSpriteSize')&&car.includes('raceScale')&&car.includes('previewScale'),'per-car contain/visual scale renderer missing');assert(car.includes('this.livery.collision')||car.includes('const collision=this.livery.collision'),'per-car collision metadata path missing');assert(car.includes('Math.min(maxLength/iw,maxWidth/ih)')&&car.includes('visualLength')&&car.includes('visualWidth'),'object-fit contain renderer missing');assert(garage.includes("'preview'"),'garage preview should use independent preview scale');
console.log(JSON.stringify({basic:basic.length,sport:sport.length,premium:premium.length,porschePrice:p.price,saveVersion:s.saveVersion},null,2));
