const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const auth=fs.readFileSync(path.join(root,'src','auth.mjs'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const account=fs.readFileSync(path.join(root,'public','js','account.js'),'utf8');
const promo=fs.readFileSync(path.join(root,'public','js','promo.js'),'utf8');
const rootjs=fs.readFileSync(path.join(root,'public','js','root-console.js'),'utf8');
const migration=fs.readFileSync(path.join(root,'migrations','0005_referrals_promocodes.sql'),'utf8');
for(const token of ['CREATE TABLE IF NOT EXISTS referrals','CREATE TABLE IF NOT EXISTS promo_codes','CREATE TABLE IF NOT EXISTS promo_redemptions','user_registration_signals'])assert(migration.includes(token),'missing migration token '+token);
for(const token of ['REFERRAL_REWARD_CREDITS=1500','REFERRAL_MIN_INVITER_AGE_MS','REFERRAL_DAILY_LIMIT','REFERRAL_NETWORK_7D_LIMIT','SAME_DEVICE','SAME_NETWORK','DEVICE_ALREADY_USED'])assert(auth.includes(token),'missing referral anti-abuse '+token);
assert(auth.includes("inviterUsername")&&auth.includes("INVITER_NOT_FOUND")&&auth.includes("CANNOT_INVITE_SELF"),'registration referral validation missing');
for(const endpoint of ['/api/promocodes/redeem','/api/admin/promocodes'])assert(auth.includes(endpoint),'missing promo endpoint '+endpoint);
assert(auth.includes('promoAction=url.pathname.match')&&auth.includes('(toggle)$/i'),'missing promo toggle endpoint');
assert(auth.includes('UNIQUE(promo_id,user_id)')&&auth.includes('uses_count=uses_count+1'),'promo one-per-user or atomic use reservation missing');
for(const id of ['authGateInviter','accountInviter','promoBtn','promoCode','rootPanePromocodes','rootPromoCode','rootPromoList'])assert(html.includes(`id="${id}"`),'missing UI '+id);
assert(account.includes('deviceId:installId()')&&account.includes('inviterUsername:'),'registration client does not send anti-abuse/referral data');
assert(account.includes('refreshCloud:loadCloud'),'promo live cloud refresh hook missing');
assert(promo.includes('/api/promocodes/redeem')&&promo.includes('refreshCloud'),'promo redemption client wiring missing');
assert(rootjs.includes("'promocodes'")&&rootjs.includes('/api/admin/promocodes')&&rootjs.includes('savePromocode')&&rootjs.includes('loadPromocodes'),'root promo manager missing');
console.log('referral_promo_smoke: OK');
