-- Velocity Apex staff administration/support system.
-- Runtime also creates these tables with CREATE TABLE IF NOT EXISTS.
CREATE TABLE IF NOT EXISTS staff_admins (user_id TEXT PRIMARY KEY,level INTEGER NOT NULL CHECK(level BETWEEN 1 AND 5),active INTEGER NOT NULL DEFAULT 1,appointed_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,appointed_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS staff_admin_warnings (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,reason TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,created_by TEXT NOT NULL,resolved_at INTEGER,resolved_by TEXT);
CREATE TABLE IF NOT EXISTS support_tickets (ticket_no INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,type TEXT NOT NULL,reporter_user_id TEXT NOT NULL,target_user_id TEXT,target_admin_user_id TEXT,category TEXT NOT NULL,description TEXT NOT NULL,evidence_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'new',assigned_admin_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,closed_at INTEGER);
CREATE TABLE IF NOT EXISTS support_messages (id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id TEXT NOT NULL,author_user_id TEXT NOT NULL,author_role TEXT NOT NULL,message TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS player_mutes (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_by TEXT NOT NULL,ticket_id TEXT,revoked_at INTEGER,revoked_by TEXT);
CREATE TABLE IF NOT EXISTS staff_daily_work (user_id TEXT NOT NULL,day TEXT NOT NULL,questions_closed INTEGER NOT NULL DEFAULT 0,reports_closed INTEGER NOT NULL DEFAULT 0,active_ms INTEGER NOT NULL DEFAULT 0,reopened INTEGER NOT NULL DEFAULT 0,reversed_actions INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL,PRIMARY KEY(user_id,day));
CREATE TABLE IF NOT EXISTS staff_presence (user_id TEXT PRIMARY KEY,last_heartbeat INTEGER NOT NULL,last_day TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS staff_reports (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,day TEXT NOT NULL,level INTEGER NOT NULL,snapshot_json TEXT NOT NULL,calculated_salary INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',owner_comment TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,reviewed_at INTEGER,reviewed_by TEXT,paid_amount INTEGER NOT NULL DEFAULT 0,UNIQUE(user_id,day));
CREATE TABLE IF NOT EXISTS staff_actions (id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,target_user_id TEXT,action TEXT NOT NULL,reason TEXT NOT NULL,duration_ms INTEGER NOT NULL DEFAULT 0,ticket_id TEXT,created_at INTEGER NOT NULL,revoked_at INTEGER,revoked_by TEXT);
