const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const auth=fs.readFileSync(path.join(root,'src','auth.mjs'),'utf8');
const worker=fs.readFileSync(path.join(root,'src','worker.mjs'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const game=fs.readFileSync(path.join(root,'public','js','game.js'),'utf8');
const account=fs.readFileSync(path.join(root,'public','js','account.js'),'utf8');
const wrangler=fs.readFileSync(path.join(root,'wrangler.jsonc'),'utf8');
for(const endpoint of ['/api/auth/me','/api/auth/register','/api/auth/login','/api/auth/logout','/api/account/save'])assert(auth.includes(endpoint),`missing ${endpoint}`);
assert(auth.includes("HttpOnly"),'session cookie must be HttpOnly');
assert(auth.includes("SameSite=Lax"),'session cookie must be SameSite=Lax');
assert(auth.includes("PBKDF2")&&auth.includes("SHA-256"),'password hashing must use PBKDF2/SHA-256');
const iterMatch=auth.match(/const PASSWORD_ITERATIONS=(\d+);/);
assert(iterMatch&&Number(iterMatch[1])<=100000,'PBKDF2 iterations must stay within Cloudflare Workers Web Crypto limit');
assert(auth.includes("token_hash"),'server must store hashed session token');
assert(worker.includes('handleAuthRequest'),'worker must route account API');
assert(html.includes('id="accountBtn"')&&html.includes('js/account.js'),'account UI must be loaded');
assert(account.includes('velocity-account-save')&&game.includes('velocity-account-save'),'cloud save event wiring missing');
assert(game.includes('VelocityAccount?.queueSave'),'game save must enqueue cloud sync');
assert(wrangler.includes('"binding": "DB"')&&wrangler.includes('velocity-apex-db'),'D1 binding missing');
console.log('account_auth_smoke: OK (D1 binding + auth endpoints + secure cookie + cloud save wiring)');
